# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hello.proto", :syntax => :proto3) do
    add_message "grpcserver.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "grpcserver.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Grpcserver
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpcserver.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpcserver.HelloReply").msgclass
end
