# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'grpcserver'

require 'grpc'
require 'hello_pb'

module Grpcserver
  module Greeter
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpcserver.Greeter'

      # Sends a greeting
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
