spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: movies
          uri: lb://MOVIES
          predicates:
            - Path=/movies/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
    registerWithEureka: true
    fetchRegistry: false
  instance:
    hostname: localhost
