version: '3.7'
services:
  mongodb-container:
    image: mongo:latest
    container_name: "movie-ratings"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
